title: MJGLANCY
description: Mixed
template:
  repo: mjglancy-template
  name: mjglancy
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
